### ISSUE TITLE
DMS ETL crashes when it fails to delete annotation

### ISSUE THREAD

**Issue by dazza-codes** [sul-dlss/annotations2triannon#22]
The stack trace is:

``` ruby
Annotation cleanup:
/home/dlweber/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/triannon-client-0.4.0/lib/triannon-client/triannon_client.rb:62:in `rescue in delete_annotation': undefined method `code' for nil:NilClass (NoMethodError)
        from /home/dlweber/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/triannon-client-0.4.0/lib/triannon-client/triannon_client.rb:51:in `delete_annotation'
        from /home/dlweber/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/annotations2triannon-0.4.0/lib/annotations2triannon/annotation_tracker.rb:98:in `block in delete_annotations'
        from /home/dlweber/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/annotations2triannon-0.4.0/lib/annotations2triannon/annotation_tracker.rb:97:in `each'
        from /home/dlweber/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/annotations2triannon-0.4.0/lib/annotations2triannon/annotation_tracker.rb:97:in `delete_annotations'
        from /home/dlweber/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/annotations2triannon-0.4.0/bin/dms.rb:67:in `<top (required)>'
        from /home/dlweber/.rbenv/versions/2.2.2/bin/dms.rb:23:in `load'
        from /home/dlweber/.rbenv/versions/2.2.2/bin/dms.rb:23:in `<main>'
```

**Comment by dazza-codes** [comment]
This was likely fixed by a fix of the triannon-client to ensure it only tries to get a response.code from a RestClient::Response instance.
